### PR TITLE
check src/brave/brave_sync/extension for npm vulnerabilities

### PR DESCRIPTION
**Pull request by diracdeltas**
fix https://github.com/brave/brave-browser/issues/2380

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions.

### CODE REVIEW

**Comment by diracdeltas** [comment]
depends on:

- [ ] https://github.com/brave/crypto/pull/17 being merged and src/brave/components/brave_sync/extension/brave-crypto updating to it
- [ ] https://github.com/brave/sync/pull/255 being merged and src/brave/components/brave_sync/extension/brave-sync updating to it

**Comment by diracdeltas** [comment]
Follow-up: https://github.com/brave/brave-core/pull/1039

**Comment by diracdeltas** [comment]
0.59.x: c83e3db1720c3891f9319d9ca2fd6b6588b710a5
master / 0.60.x: c46033a189bb77f1f28109164494815927c58756

**Comment by diracdeltas** [comment]
Adding uplift request, per https://github.com/brave/brave-browser/issues/2380#issuecomment-445077338

**Comment by kjozwiak** [comment]
@diracdeltas approved uplift request to `0.58.x` after deliberating with @rebron 👍 Please remove/add all needed labels and move the appropriate issue to the correct milestone.

**Comment by diracdeltas** [comment]
0.58.x: f755d06a46dec9fb7c2d08488ee0d565415a2e5d

**Pull request merged**
