### PR TITLE
added option to output test results to file

### PR DESCRIPTION
**Pull request by mihaiplesa**
Added option to specify file for test output (results).

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions.

### CODE REVIEW

**Comment by bsclifton** [comment]
@mihaiplesa added `merged/0.56.x` label; is this supposed to go into `0.55.x` also? If so, let's merge and put the `merged/0.55.x` on it instead 😄 I also noticed the issue this fixes is still open?

**Comment by mihaiplesa** [comment]
Yes, I created the issue after the PR so it didn't get closed, should have got into 0.55.x as well.

**Comment by bsclifton** [comment]
@mihaiplesa ok great- I just merged with 0.55.x with https://github.com/brave/brave-browser/commit/e21fb29829a689d4ff72ea51a3497288740f22dc 😄

**Comment by mihaiplesa** [comment]
boom!

**Pull request merged**
