### PR TITLE
Add intruction on how to install on Solus, fixes #2231

### LINKED ISSUE #2231: Add Solus instructions to installation documentation
## Description 
Add Solus instructions to installation documentation

### Additional Information
The package is maintained mostly by [alecbcs](https://dev.getsol.us/p/alecbcs/) and somewhat by me. We will do our best to keep it up to date at all time!

### PR DESCRIPTION
**Pull request by Jacalz**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.

## Test Plan:
Installed brave from the Solus repository...

Fixes: #2231

### CODE REVIEW

**Comment by mihaiplesa** [comment]
This seems to be pointing to old the Brave based on Muon @Jacalz not the new Brave Core based on Chromium.

The package name should be `brave-browser` for consistency, and we might want to provide it on the other channels as well (`brave-browser-beta`, `brave-browser-dev`) if that's possible.

**Comment by mihaiplesa** [comment]
This is what I'm getting when installing and starting, looks like it's Brave Muon which will be unsupported soon.

solus2

If I update the repos using `sudo eopkg update-repo` and the install again it gets Brave Core 0.56.12 as seen below (latest release version is 0.56.15).

solus3

My suggestion would be to remove old versions based on Muon from the repo and provide the latest release one. Thoughts on this and package naming @mbacchi?

**Comment by Jacalz** [comment]
That is weird, I get the latest version when I install it. Might e an issue with cached repo versions, but I don’t really know. As far as 0.56.15 I have a patch waiting for review to get it updated, Linux is a complicated machine, nothing is as easy as it looks...

**Comment by mihaiplesa** [comment]
Good part is that upgrade from Muon to Core will be seamless for our users if we keep the `brave` package name.

**Comment by mihaiplesa** [comment]
Cool, let's wait till we get @mbacchi's opinion.

**Comment by Jacalz** [comment]
Sure, sounds like a good idea 👍

**Pull request closed without merging**
