### PR TITLE
no more browser code in this repo

### PR DESCRIPTION
**Pull request by mihaiplesa**
Resolves 

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A
  - [ ] https://github.com/brave/brave-browser/wiki/Brave-Wallet

### CODE REVIEW

**Comment by farisbst** [comment]
Nice

**Review by Yahwehloves — APPROVED** [review]

**Comment by Rathmox** [comment]
Where are you planning to put the code then ?

**Comment by mihaiplesa** [comment]
@Rathmox it already is in https://github.com/brave/brave-core which doesn't need this repo anymore.

**Comment by Rathmox** [comment]
@mihaiplesa Oh, ok, so this repo will only be an issue tracker ?

**Comment by mihaiplesa** [comment]
@Rathmox it already is.

**Comment by elvey** [comment]
Its not just an issue tracker. It also hosts the wiki.  (Should it be moved?)

**Review by Eason-S-Lu — CHANGES_REQUESTED** [review]
I don't think it is a good idea due to backward compatibility.

**Comment by mihaiplesa** [comment]
@bridiver I guess the repo we'd keep is this one rather than brave-core and we just port the source code.

**Comment by bridiver** [comment]
> @bridiver I guess the repo we'd keep is this one rather than brave-core and we just port the source code.

well, that's been a subject of much discussion in the slack channel and I think we decided that was going to cause too many headaches for devs

**Comment by Eason-S-Lu** [comment]
Maybe git submodules?

**Comment by bridiver** [comment]
> Maybe git sub-modules? Like make brave-core a sub-modules of brave-browser?

Not sure how that helps the situation. It still leaves us with two repos, but I'm going to close this PR because it's not really relevant anymore. brave-core is independent of brave-browser and can be used without it. The main issue we have now is trying to somehow integrate issues/PRs into a single repo

**Pull request closed without merging**
