### PR TITLE
Use two issue templates, one for issues and one for fature requests

### LINKED ISSUE #2435: Improve issue templates
## Description 

Update issue templates to have one for feature requests and one for bug reports.

### PR DESCRIPTION
**Pull request by Jacalz**
Fixes #2435

## Test plan:

Go to https://github.com/Jacalz/brave-browser/issues

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Tagged reviewers and labelled the pull request as needed.

### CODE REVIEW

**Comment by srirambv** [comment]
Does the user get a choice when they click on New issue?

**Comment by Jacalz** [comment]
Yes they do, I will se to set up my fork for testing @srirambv

**Comment by Jacalz** [comment]
They are now set up for testing [here](https://github.com/Jacalz/brave-browser/issues)

**Comment by srirambv** [comment]
This is awesome but not sure how effective this will be. Issues are organised based on labels and help in triage so having different template doesn't add any value in my opinion. We will still end up adding labels to track issues irrespective of which template is used to create an issue. And majority of issues would end up removing template and adding a note so don't think this will help much

**Comment by Jacalz** [comment]
Will close this then

**Comment by NejcZdovc** [comment]
I think this would be useful as if you are adding feature you will not need to remove boilerplate with steps from a bug report (this is what I normally do).

**Comment by Jacalz** [comment]
It was what I thought too, will reopen then...

**Comment by srirambv** [comment]
I actually like the idea of giving the option to users before logging issue but not really sure how effectively it will be. Have seen time and time again users not adhering to posting rules and just put a one liner (even for issues) and they stop responding after couple of comments and it just ends up piling up the backlog. Am pretty sure some users would just use the wrong one to log issue and feature request. I highly doubt anyone would justify the usecase for feature request. Doesn't happen on community as well, even with clear instructions its going to be  **_"please implement this because I use it"_**

Personally feel its going to be overwork if we do add options. Although its a neat feature i'd like to avoid it. 

cc: @brave/legacy_qa to chime in on their thoughts

**Comment by Jacalz** [comment]
Anyone interested in this PR, or should I just close it?

**Comment by bsclifton** [comment]
Let's close this for now. The current process isn't too painful

Thanks for the PR, though 😄

**Pull request closed without merging**
