### PR TITLE
Update to use our new Chromium mirror (uplift to 1.7)

### PR DESCRIPTION
**Pull request by bsclifton**
Includes the following (merged in this order)
- [update chromium src to use brave-chromium](https://github.com/brave/brave-browser/pull/9039)
- [Allow src repo change](https://github.com/brave/brave-browser/pull/9017)
- [don't change the brave-core remote](https://github.com/brave/brave-browser/pull/9173)
- [auto-generate the chromium repo url if it is not specified](https://github.com/brave/brave-browser/pull/9100)
- [simplify init/sync and make them compatible with GIT_CACHE_DIR](https://github.com/brave/brave-browser/pull/9142)

### CODE REVIEW

**Comment by bsclifton** [comment]
Trying to fix git cache on servers first - let's not merge this please

**Comment by bsclifton** [comment]
Closing as I believe I found a fix. See https://bravesoftware.slack.com/archives/CA5FPHWLF/p1587189601497800 for more information

**Comment by bsclifton** [comment]
Windows ran into a problem during init:
```
10:14:23  [0:06:20] Cloning into 'C:\.7.x\src\third_party\_gclient_webrtc_tbqvqu'...
10:14:23  [0:06:21] done.
10:14:23  [0:06:21] Finished running: git rev-parse --verify FETCH_HEAD
10:14:23  [0:06:21] fatal: git upload-pack: not our ref 7502134e7e428aaa5c42c8f18c87e8cfda7f87a4
10:14:23  [0:06:21] fatal: remote error: upload-pack: not our ref 7502134e7e428aaa5c42c8f18c87e8cfda7f87a4
10:14:23  [0:06:22] fatal: git upload-pack: not our ref 7502134e7e428aaa5c42c8f18c87e8cfda7f87a4
10:14:23  [0:06:22] fatal: remote error: upload-pack: not our ref 7502134e7e428aaa5c42c8f18c87e8cfda7f87a4
10:14:23  [0:06:23] fatal: git upload-pack: not our ref 7502134e7e428aaa5c42c8f18c87e8cfda7f87a4
10:14:23  [0:06:23] fatal: remote error: upload-pack: not our ref 7502134e7e428aaa5c42c8f18c87e8cfda7f87a4
10:14:23  [0:06:25] fatal: git upload-pack: not our ref 7502134e7e428aaa5c42c8f18c87e8cfda7f87a4
10:14:23  [0:06:25] fatal: remote error: upload-pack: not our ref 7502134e7e428aaa5c42c8f18c87e8cfda7f87a4
10:14:23  [0:06:29] _____ Conflicting directory found in C:\.7.x\src\third_party\webrtc. Moving to C:\.7.x\_bad_scm\src\third_party\webrtcl1pqxb.
10:14:23  [0:06:29] 
10:14:23  [0:06:29] 
10:14:23  ________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress --shared C:\Users\Administrator\cache\webrtc.googlesource.com-src 
10:14:23  C:\.7.x\src\third_party\_gclient_webrtc_dtwkwg' in 'C:\.7.x'
10:14:23  
10:14:23  [0:06:29] Cloning into 'C:\.7.x\src\third_party\_gclient_webrtc_dtwkwg'...
10:14:23  [0:06:29] done.
10:14:23  [0:06:30] Finished running: git rev-parse --verify FETCH_HEAD
10:14:23  [0:06:30] fatal: git upload-pack: not our ref 7502134e7e428aaa5c42c8f18c87e8cfda7f87a4
10:14:23  [0:06:30] fatal: remote error: upload-pack: not our ref 7502134e7e428aaa5c42c8f18c87e8cfda7f87a4
10:14:23  [0:06:30] fatal: git upload-pack: not our ref 7502134e7e428aaa5c42c8f18c87e8cfda7f87a4
10:14:23  [0:06:30] fatal: remote error: upload-pack: not our ref 7502134e7e428aaa5c42c8f18c87e8cfda7f87a4
10:14:23  [0:06:32] fatal: git upload-pack: not our ref 7502134e7e428aaa5c42c8f18c87e8cfda7f87a4
10:14:23  [0:06:32] fatal: remote error: upload-pack: not our ref 7502134e7e428aaa5c42c8f18c87e8cfda7f87a4
10:14:23  [0:06:34] fatal: git upload-pack: not our ref 7502134e7e428aaa5c42c8f18c87e8cfda7f87a4
10:14:23  [0:06:34] fatal: remote error: upload-pack: not our ref 750
10:14:23  2134e7e428aaa5c42c8f18c87e8cfda7f87a4
10:14:23  ----------------------------------------
10:14:23  Error: Command 'git -c core.deltaBaseCacheLimit=2g fetch origin 7502134e7e428aaa5c42c8f18c87e8cfda7f87a4' returned non-zero exit status 128 in C:\.7.x\src\third_party\webrtc
```
https://ci.brave.com/job/brave-browser-build-pr/job/PR-9304/3/execution/node/245/log/

**Comment by bridiver** [comment]
why are we uplifting this?

**Comment by bridiver** [comment]
it would need this as well https://github.com/brave/brave-browser/pull/9343 and I don't think we've had this in master long enough to uplift it

**Comment by bsclifton** [comment]
Closing out in favor of a smaller PR, similar to https://github.com/brave/brave-browser/pull/9359

**Pull request closed without merging**
