### PR TITLE
use http url for brave-core

### PR DESCRIPTION
**Pull request by mbacchi**
## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions

### CODE REVIEW

**Comment by bbondy** [comment]
thanks!

**Comment by bsclifton** [comment]
@mbacchi just curious: is this preferred so that you can build without having ssh setup?

**Comment by bsclifton** [comment]
@mbacchi the only problem with HTTPS is that when you do a push, you need to authenticate every time. When working locally, I usually `git remote remove origin` and then `git remote add origin git@...` all of the HTTPS repos to prevent that

**Comment by evq** [comment]
@bsclifton if you set up a git URL rewrite rule then you can avoid having to modify each HTTPS repo individually - https://git-scm.com/docs/git-config#git-config-urlltbasegtinsteadOf

The command below will modify your git config to rewrite HTTPS github remotes to use SSH:
```
git config --global url.ssh://git@github.com/.insteadOf https://github.com/
```

**Comment by bsclifton** [comment]
@evq that is awesome! Thank you 😄

**Pull request merged**
