### PR TITLE
 Apply patches now only selectively resets repo paths and applies patches

### PR DESCRIPTION
**Pull request by petemill**
### Goal
Allow switching between brave-core branches and not incurring a lengthy build because all ~400 chromium source files were reset and had patches re-applied.
Instead, only reset target files and apply patches when appropriate: when either the patch file has changed or the chromium source file has been modified.

### This PR

1. "reset" a project repo (`chromium` or `brave-core`) only when the working directory commit reference does not match the target branch commit reference. Before, this happened every sync.
2. "reset" and re-apply patched individual files _only_ when either the .patch file has changed, or the patched target file has changed. Before, this happened every sync.
3. Applies any v8 patches found in `brave-core/patches/v8` directory (created by #4955)
4. Adds more visual logging to the `sync` command, including handling patch apply errors.
5. Create unit tests for patching under `npm run test:scripts`

The bulk of the code is for 2), which is a method to detect when any .patch file needs to be applied again. 1) is a pre-requisite since if the entire codebase is being `git reset --hard` then all patched files will be marked as modified at that point.

This is achieved by writing a corresponding .patchinfo file for each .patch file that is applied. This file contains a checksum of the .patch file, as well as a checksum of each target source file that the patch applies to. The checksum is calculated _after_ the patch is applied.

Here's an example from `src/brave/patches/ui-base-BUILD.gn.patchinfo`
```
{
  "schemaVersion":1,
  "patchChecksum": "fd732082c96f1e919f9549b07f0dd2a308636d88de5ecd76d71620ace882dadf",
  "appliesTo": [
    {
      "path": "ui/base/BUILD.gn",
      "checksum": "ecb8bd895be248c124002eb1fb98aaa9f7e0c16fbf38616426645768086c096d"
    }
  ]
}
```

**Note** that `npm run sync -- --init` will still always reset and re-apply all patches.
`npm run sync -- --all` however will run this more selective algorithm.

~Needs https://github.com/brave/brave-core/pull/2780 to be merged first, which ignores the .patchinfo files in brave-core git.~

Fix https://github.com/brave/brave-browser/issues/3184

#### First run
image

#### Nothing needs patching
image

#### A few files need patching
image

#### Patch file was removed, source gets reset
image

#### Error handling a patch gone wrong (perhaps due to merge conflict)
image

#### More logging about pulling latest commits to project repo directories
image

render1561587196239

#### Automated
`npm run test:scripts`
image

#### Manual
- Using current master, get latest and run a sync
- Switch to this branch and run `npm run sync -- --all`
  - Expect: all patches are re-applied
- Run `npm run sync -- --all` again
  - Expect: no patches are re-applied, and the subsequent build has nothing to do
- Modify a single patch file (`echo " " >> mypatch.patch`)
  - Expect: only that patch file is modified
- Manually edit or reset a chromium target file (`cd src && git checkout chromium/file.cc`)
- Run `npm run sync -- --all` again
   - Expect: only that chormium file's patch file is re-applied

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [x] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [x] Windows
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [x] Requested a security/privacy review as needed. https://github.com/brave/internal/issues/603
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions.

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by bsclifton** [comment]
Interestingly enough- I had to run `npm run init` (not `npm run sync -- --all` because this wouldn't update `src/chrome/VERSION`

**Comment by petemill** [comment]
@bsclifton what was the error? I’m not sure what init would do differently that would cause VERSION to get different content, but I’d love to replicate

**Comment by bsclifton** [comment]
@petemill well- I had an old version of master (old `brave-core`) and then I just grabbed your `brave-browser` branch here and ran `npm run sync -- --all` (of course, after running `rm -rf node_modules && npm i` to get the new modules you described)

After doing so, `src/chrome/VERSION` was NOT updated (tried 3 times) ☹️ I then ran `npm run init` and it was updated as expected. You don't get the error (version mismatch) until you go to compile

**Comment by petemill** [comment]
Added @mihaiplesa as a reviewer since I modified Jenkins config to run the new `npm run test:scripts` command on all platforms.

Predictably, this tests some script library code, such as the patch apply process.

**Comment by mihaiplesa** [comment]
@petemill just noticed now in the `Jenkinsfile` that it's set to run before `init`, is that the right place?

**Comment by petemill** [comment]
> @petemill just noticed now in the `Jenkinsfile` that it's set to run before `init`, is that the right place?

@mihaiplesa yes - since this tests some of the code that is run during init, I think we would want to fail before that.

**Comment by bsclifton** [comment]
Running before `init` should be safe, since `brave-core` repo isn't needed (the tests are specific to this repo). If tests were using `brave-core` in any way, then it would have to be after init 👍

**Comment by petemill** [comment]
Just investigating why the script tests are failing in Windows. They work find in my Windows VM.

<details>
<summary>
Here's the error:
</summary>
```
15:11:37  
15:11:37  > brave@0.69.50 test:scripts C:\jenkins\workspace\brave-browser-build-pr_PR-4993
15:11:37  > jest lib scripts "--verbose"
15:11:37  
15:11:39  powershell.exe : PASS lib/calculateFileChecksum.test.js
15:11:39  At C:\jenkins\workspace\brave-browser-build-pr_PR-4993@tmp\durable-b284de10\powershellWrapper.ps1:3 char:1
15:11:39  + & powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -Comm ...
15:11:39  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
15:11:39      + CategoryInfo          : NotSpecified: (PASS lib/calculateFileChecksum.test.js:String) [], RemoteException
15:11:39      + FullyQualifiedErrorId : NativeCommandError
15:11:39   
15:11:39    âˆš generates a checksum (20ms)
15:11:39  
15:11:39    âˆš checksum is stable (3ms)
15:11:39  
15:11:39    âˆš checksum changes when file contents change (6ms)
15:11:39  
15:11:39  
15:11:39  
15:11:40  FAIL lib/gitPatcher.test.js
15:11:40  
15:11:40    Apply Patches
15:11:40  
15:11:40      Ã— applies simple patch to unmodified original (149ms)
15:11:40  
15:11:40      Ã— does not apply patch to still-patched (119ms)
15:11:40  
15:11:40      Ã— resets target file if patch file is removed (118ms)
15:11:40  
15:11:40      Ã— handles missing file when resets target file if patch file is removed (119ms)
15:11:40  
15:11:40      Ã— handles bad patch file (120ms)
15:11:40  
15:11:40      Ã— handles no patch dir (122ms)
15:11:40  
15:11:40      Ã— handles no repo dir (128ms)
15:11:40  
15:11:40  
15:11:40  
15:11:40    â—� Apply Patches â€º applies simple patch to unmodified original
15:11:40  
15:11:40      Program git exited with error code 128.
15:11:40  
15:11:40        59 |         }
15:11:40        60 |         if (hasFailed) {
15:11:40      > 61 |           const err = new Error(`Program ${cmd} exited with error code ${statusCode}.`)
15:11:40           |                       ^
15:11:40        62 |           err.stderr = stderr
15:11:40        63 |           err.stdout = stdout
15:11:40        64 |           reject(err)
15:11:40  
15:11:40        at ChildProcess.prog.on.statusCode (lib/util.js:61:23)
15:11:40  
15:11:40    â—� Apply Patches â€º applies simple patch to unmodified original
15:11:40  
15:11:40      TypeError: Cannot read property 'applyPatches' of undefined
15:11:40  
15:11:40        78 |   test('applies simple patch to unmodified original', async function () {
15:11:40        79 |     validate()
15:11:40      > 80 |     const affectedPaths = await gitPatcher.applyPatches()
15:11:40           |                                            ^
15:11:40        81 |     // test file contents
15:11:40        82 |     const testFile1Content = await fs.readFile(testFile1Path, writeReadFileOptions)
15:11:40        83 |     expect(testFile1Content).toBe(file1ModifiedContent)
15:11:40  
15:11:40        at Object.applyPatches (lib/gitPatcher.test.js:80:44)
15:11:40  
15:11:40    â—� Apply Patches â€º does not apply patch to still-patched
15:11:40  
15:11:40      Program git exited with error code 128.
15:11:40  
15:11:40        59 |         }
15:11:40        60 |         if (hasFailed) {
15:11:40      > 61 |           const err = new Error(`Program ${cmd} exited with error code ${statusCode}.`)
15:11:40           |                       ^
15:11:40        62 |           err.stderr = stderr
15:11:40        63 |           err.stdout = stdout
15:11:40        64 |           reject(err)
15:11:40  
15:11:40        at ChildProcess.prog.on.statusCode (lib/util.js:61:23)
15:11:40  
15:11:40    â—� Apply Patches â€º does not apply patch to still-patched
15:11:40  
15:11:40      TypeError: Cannot read property 'applyPatches' of undefined
15:11:40  
15:11:40        93 |     const testFile1StatsInitial = await fs.stat(testFile1Path)
15:11:40        94 |     // apply once
15:11:40      > 95 |     await gitPatcher.applyPatches()
15:11:40           |                      ^
15:11:40        96 |     // get modified file time
15:11:40        97 |     const testFile1StatsModified = await fs.stat(testFile1Path)
15:11:40        98 |     // apply again
15:11:40  
15:11:40        at Object.applyPatches (lib/gitPatcher.test.js:95:22)
15:11:40  
15:11:40    â—� Apply Patches â€º resets target file if patch file is removed
15:11:40  
15:11:40      Program git exited with error code 128.
15:11:40  
15:11:40        59 |         }
15:11:40        60 |         if (hasFailed) {
15:11:40      > 61 |           const err = new Error(`Program ${cmd} exited with error code ${statusCode}.`)
15:11:40           |                       ^
15:11:40        62 |           err.stderr = stderr
15:11:40        63 |           err.stdout = stdout
15:11:40        64 |           reject(err)
15:11:40  
15:11:40        at ChildProcess.prog.on.statusCode (lib/util.js:61:23)
15:11:40  
15:11:40    â—� Apply Patches â€º resets target file if patch file is removed
15:11:40  
15:11:40      TypeError: Cannot read property 'applyPatches' of undefined
15:11:40  
15:11:40        110 |     validate()
15:11:40        111 |     // apply once
15:11:40      > 112 |     await gitPatcher.applyPatches()
15:11:40            |                      ^
15:11:40        113 |     // remove patch file
15:11:40        114 |     await fs.unlink(testFile1PatchPath)
15:11:40        115 |     // apply again
15:11:40  
15:11:40        at Object.applyPatches (lib/gitPatcher.test.js:112:22)
15:11:40  
15:11:40    â—� Apply Patches â€º handles missing file when resets target file if patch file is removed
15:11:40  
15:11:40      Program git exited with error code 128.
15:11:40  
15:11:40        59 |         }
15:11:40        60 |         if (hasFailed) {
15:11:40      > 61 |           const err = new Error(`Program ${cmd} exited with error code ${statusCode}.`)
15:11:40           |                       ^
15:11:40        62 |           err.stderr = stderr
15:11:40        63 |           err.stdout = stdout
15:11:40        64 |           reject(err)
15:11:40  
15:11:40        at ChildProcess.prog.on.statusCode (lib/util.js:61:23)
15:11:40  
15:11:40    â—� Apply Patches â€º handles missing file when resets target file if patch file is removed
15:11:40  
15:11:40      TypeError: Cannot read property 'applyPatches' of undefined
15:11:40  
15:11:40        127 |     validate()
15:11:40        128 |     // apply once
15:11:40      > 129 |     await gitPatcher.applyPatches()
15:11:40            |                      ^
15:11:40        130 |     // remove patch file
15:11:40        131 |     await fs.unlink(testFile1PatchPath)
15:11:40        132 |     // remove target file
15:11:40  
15:11:40        at Object.applyPatches (lib/gitPatcher.test.js:129:22)
15:11:40  
15:11:40    â—� Apply Patches â€º handles bad patch file
15:11:40  
15:11:40      Program git exited with error 
15:11:40  code 128.
15:11:40  
15:11:40        59 |         }
15:11:40        60 |         if (hasFailed) {
15:11:40      > 61 |           const err = new Error(`Program ${cmd} exited with error code ${statusCode}.`)
15:11:40           |                       ^
15:11:40        62 |           err.stderr = stderr
15:11:40        63 |           err.stdout = stdout
15:11:40        64 |           reject(err)
15:11:40  
15:11:40        at ChildProcess.prog.on.statusCode (lib/util.js:61:23)
15:11:40  
15:11:40    â—� Apply Patches â€º handles bad patch file
15:11:40  
15:11:40      TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
15:11:40  
15:11:40        144 |     validate()
15:11:40        145 |     // Create an invalid patch
15:11:40      > 146 |     await fs.writeFile(testFile1PatchPath, 'bad patch', writeReadFileOptions)
15:11:40            |              ^
15:11:40        147 |     const status = await gitPatcher.applyPatches()
15:11:40        148 |     expect(status).toHaveLength(1)
15:11:40        149 |     expect(status[0]).toHaveProperty('patchPath', testFile1PatchPath) 
15:11:40  
15:11:40        at go$writeFile (node_modules/graceful-fs/graceful-fs.js:94:14)
15:11:40        at Object.writeFile (node_modules/graceful-fs/graceful-fs.js:91:12)
15:11:40        at Promise (node_modules/universalify/index.js:13:12)
15:11:40        at Object.writeFile (node_modules/universalify/index.js:7:14)
15:11:40        at Object.writeFile (lib/gitPatcher.test.js:146:14)
15:11:40  
15:11:40    â—� Apply Patches â€º handles no patch dir
15:11:40  
15:11:40      Program git exited with error code 128.
15:11:40  
15:11:40        59 |         }
15:11:40        60 |         if (hasFailed) {
15:11:40      > 61 |           const err = new Error(`Program ${cmd} exited with error code ${statusCode}.`)
15:11:40           |                       ^
15:11:40        62 |           err.stderr = stderr
15:11:40        63 |           err.stdout = stdout
15:11:40        64 |           reject(err)
15:11:40  
15:11:40        at ChildProcess.prog.on.statusCode (lib/util.js:61:23)
15:11:40  
15:11:40    â—� Apply Patches â€º handles no repo dir
15:11:40  
15:11:40      Program git exited with error code 128.
15:11:40  
15:11:40        59 |         }
15:11:40        60 |         if (hasFailed) {
15:11:40      > 61 |           const err = new Error(`Program ${cmd} exited with error code ${statusCode}.`)
15:11:40           |                       ^
15:11:40        62 |           err.stderr = stderr
15:11:40        63 |           err.stdout = stdout
15:11:40        64 |           reject(err)
15:11:40  
15:11:40        at ChildProcess.prog.on.statusCode (lib/util.js:61:23)
15:11:40  
15:11:40  Test Suites: 1 failed, 1 passed, 2 total
15:11:40  Tests:       7 failed, 3 passed, 10 total
15:11:40  Snapshots:   0 total
15:11:40  Time:        2.991s
15:11:40  Ran all test suites matching /lib|scripts/i.
15:11:40  
15:11:40  npm
15:11:40   
15:11:40  ERR!
15:11:40   
15:11:40  code
15:11:40   ELIFECYCLE
15:11:40  
15:11:40  npm
15:11:40   
15:11:40  ERR!
15:11:40   
15:11:40  errno
15:11:40   1
15:11:40  
15:11:40  npm
15:11:40   
15:11:40  ERR!
15:11:40   brave@0.69.50 test:scripts: `jest lib scripts "--verbose"`
15:11:40  
15:11:40  npm
15:11:40   
15:11:40  ERR!
15:11:40   Exit status 1
15:11:40  
15:11:40  npm
15:11:40   
15:11:40  ERR!
15:11:40   
15:11:40  
15:11:40  npm
15:11:40   
15:11:40  ERR!
15:11:40   Failed at the brave@0.69.50 test:scripts script.
15:11:40  
15:11:40  npm
15:11:40   
15:11:40  ERR!
15:11:40   This is probably not a problem with npm. There is likely additional logging output above.
15:11:40  
15:11:40  
15:11:40  
15:11:40  npm
15:11:40   
15:11:40  ERR!
15:11:40   A complete log of this run can be found in:
15:11:40  
15:11:40  npm 
15:11:40  ERR!
15:11:40       C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-07-10T22_11_38_752Z-debug.log
15:11:40  
```
</details>

**Comment by petemill** [comment]
Test issue is resolved. All relevant build steps in Jenkins across platforms passed.
I've also personally tested this across different types of branch changes: brave-core switches, chromium major version switches - including patch files removed, added, modified - and everything has behaved. I also chatted with @bridiver and made some recommended changes to do with putting some additional logic in a `lib/` module instead of bloating `scripts/sync.js` GTG IMO @bsclifton!

**Pull request merged**
