### PR TITLE
Enable vaapi support

### LINKED ISSUE #1024: Enable video decoding with vaapi by default
## Description
From reddit thread:
https://www.reddit.com/r/BATProject/comments/9dkbpi/the_rewrite_of_brave_named_brave_core_is/

"On Linux, we definitely need to get Hardware Video decoding with vaapi working. (Chromium does not enable the compile flag by default)"

Please verify this is the case that it's on with Chrome and enable with Brave if so.
Maybe a gn option that we can see what the default is.

### PR DESCRIPTION
**Pull request by akarshanbiswas**
Partially fixes #1024 

By default browser will blacklist all drivers on linux for vaapi decoding. 

To enable it , need to pass `--ignore-gpu-blacklist` in order to get it working since libva has problems atm with intel GPUs. I am hoping that it will be fixed in the future versions. There are a lot of activities in upstream in this.
Only adding this support on 64 bit build at the moment.

Based on this upstream commit: https://github.com/chromium/chromium/commit/31225b9c5f3f685d65f742dc129241c30c32157c

## Test Plan:
* Check if build succeeds.
* Run brave with `--ignore-gpu-blacklist` flag and see if the video is playing with hardware decoders or not. ( video needs to be supported by hardware)

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [ ] macOS
  - [x] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests && npm run test-security`) on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions.

### CODE REVIEW

**Comment by maximbaz** [comment]
Hey, I'm maintainer of `chromium-vaapi` for Arch Linux and I'm eager to try your PR 🙂 Unfortunately I can't build Brave right now due to https://github.com/brave/brave-browser/issues/305, but I'm curious, don't you also need to actually have [this patch](https://aur.archlinux.org/cgit/aur.git/tree/chromium-vaapi.patch?h=chromium-vaapi) applied to make it work on non-Chrome-OS hosts?

**Comment by biswasab** [comment]
@maximbaz Hello! This is my patch from Fedora but no because few intel devices are having problem with vaapi. I opened this PR but not getting enough time to work on it. Also there is #305. It would be helpful if you try it for me. (maybe opening a github repo that I can see and contribute?) :)

**Comment by maximbaz** [comment]
I have eventually managed to compile Brave binary from your PR in a very weird way, but I can confirm that Brave that is based on Chromium 74 + your patch + `--ignore-gpu-blacklist` does indeed use HW acceleration on my Intel machine! Video is accelerated, CPU fans are silent, all is perfect 🙂 

Chromium 75 has introduced [a regression that broke VA-API](https://github.com/intel/intel-vaapi-driver/issues/456#issuecomment-500192039) for both VP9 and H264 on my Intel machine.

I would really really love to see this PR and #305 fixed, so I can add Brave to the official repositories of Arch Linux. Hopefully Chromium/Intel fixes their regression as well.

**Comment by biswasab** [comment]
@maximbaz Thank you so much for testing!!!!

**Comment by maximbaz** [comment]
@akarshanbiswas so the [patch](https://aur.archlinux.org/cgit/aur.git/tree/vaapi-fix.patch?h=chromium-vaapi) you shared on Arch forums helped fixing VA-API on Nvidia and Intel in the latest Chromium (once again thanks for that!), how do we go and include that patch in Brave, do you know? I'm not very familiar with the codebase yet, but it seems we would need to patch `brave-core`?

**Comment by akarshanbiswas** [comment]
@maximbaz I will try to contact upstream instead. Meanwhile we should move this conversation on the intel vaapi driver issue that you've mentioned to let other know of this.

**Comment by maximbaz** [comment]
While contacting upstream is definitely a correct course of action, as a packager I'm considering what it would take to maintain Brave with VA-API support, comparing to Chromium with VA-API. Suppose #305 is fixed, my build steps are just the 3 commands below, and I have a chromium patch to apply - how difficult would that be to do, do you know?

```
npm install
npm run init
npm run create_dist Release --debug_build=false --official_build=true
```

**Comment by akarshanbiswas** [comment]
@maximbaz Please create a repo and add me as a maintainer. Let me see what I can do. For now please keep this thread clean.

Brave uses npm as a build system. I'm not very good at it. The patch which I shared need to be added to brave core if I am not wrong. I need to study it first.

**Comment by cg505** [comment]
@akarshanbiswas @maximbaz Will this PR work without the chromium vaapi patch at https://aur.archlinux.org/cgit/aur.git/tree/chromium-vaapi-fix.patch?h=brave?

**Comment by maximbaz** [comment]
With this PR the browser will compile successfully, and if started with `--ignore-gpu-blacklist` hardware video acceleration will work on a certain subset of graphics cards (namely AMD and some Intel), but that patch is required to support the rest of Intel cards and all of Nvidia. 

there is a benefit of merging this PR even without that chromium patch, if that's what you are asking 😉

**Comment by akarshanbiswas** [comment]
@cg505 Yes. The normal behavior will be the same as the current release build of brave. 
The patch you mentioned fixes certain regressions on specific intel and nvidia GPUs.

Nvidia GPUs doesn't support VPP, and some Intel drivers has issues with specially few skylake and others. This is the same reason I am not enabling(removing the blacklist) it by default.

The upstream is pretty active in [fixing](https://github.com/chromium/chromium/commit/0c94f28051c5ec30d2881f253cd97beb0f0a4b2d#diff-bccebd678dde7a9e7698c5e4b166d1d7) build errors with vaapi on Linux.

**Comment by cg505** [comment]
Awesome, I was able to verify that this works for me.

**Comment by bsclifton** [comment]
@akarshanbiswas can you give this PR a rebase? This should kick off our continuous integration for Linux, which compiles + runs tests

**Comment by akarshanbiswas** [comment]
@bsclifton Sure :+1:

**Comment by akarshanbiswas** [comment]
@bsclifton Rebased to latest changes from master branch. It needs to get reviewed.

**Comment by bsclifton** [comment]
ugh forgot CI doesn't run on forks 😓 

Going to approve because @cg505 did test this out and it worked for him

**Pull request merged**
