### PR TITLE
Build: send notification to slack with list of downloads

### PR DESCRIPTION
**Pull request by petemill**
Get quick access to any build's uploaded output for quick testing by the product team (or other). I intentionally left this as occuring not only for succesful builds, but only when there's at least 1 uploaded artifact. That means that macOS may fail for example, but we can still view the Windows builds.

Should look something like this:

image

I tested this against DMing me, but I think we should create a channel called something like `#build-downloads`.

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions.

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by bsclifton** [comment]
This is amazing - will be checking out soon

**Comment by mihaiplesa** [comment]
Was thinking if we can put the links as a comment to the PR or in a Slack channel like #brave-browser-prs or #brave-browser-features (more generic, not just for downloads).

**Comment by petemill** [comment]
@bsclifton feel free to run the job in Jenkins and change the param for the slack channel to your private DM room or even #brave-browser-ci if the room specified in code doesn't yet exist. I already ran it pointed at my DMs as it took me about 20 cycles to validate the Jenkinsfile syntax (I couldn't find a local way that I had permissions to use!)

@mihaiplesa we could absolutely post to GH in the same step or a different step. As for the slack channel, the idea was to use one that wouldn't spam something used for conversation as there would be many messages posted by this for each build of each PR. And also from a UX point of view - to allow both anyone to go in and scan for recent interesting builds / find something specific, and also for a dev to go in and copy a link to a specific PR build to paste in to another room / conversation. So, push and pull!

**Comment by bsclifton** [comment]
queued up using `#brave-browser-ci` 👍 If that looks good, I'll ask folks if they can help create appropriate Slack channel 😄

**Comment by bsclifton** [comment]
Ran job manually- it worked great 😄 

Example shared here:
https://bravesoftware.slack.com/archives/CA5FPHWLF/p1566238839399200

**Pull request merged**
