### PR TITLE
Add Android issue template

### PR DESCRIPTION
**Pull request by srirambv**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection

## Test Plan:
Fixes https://github.com/brave/brave-browser/issues/7573

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions.

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by bsclifton** [comment]
@srirambv do we need to delete https://github.com/brave/brave-browser/blob/master/.github/ISSUE_TEMPLATE.md ?

I believe creating a new issue should give the user a choice, but I forget how that looks. You might turn on issues for your fork and see how it looks when creating a new issue (if needed, you can push this to master on your fork)

**Comment by srirambv** [comment]
@bsclifton  looks like this is changed with the templates generated by github settings. This now needs to be setup from the repo settings. @alegardy could you set this up?

**Comment by bsclifton** [comment]
Interesting; there is a new UI for this. I think the UI is optional though, as we use templates via the directory structure way for other repos (ex: when doing security review, etc)

Here's a screenshot of that new UI. You can setup multiple templates (including a "custom" one) and then there is a `Propose changes` button
Screen Shot 2020-01-05 at 11 01 28 PM

@alegardy let's not take any action until we figure this out 👍 

@srirambv if you fork `brave-browser` (which you did) and you delete `.github/ISSUE_TEMPLATE.md`, is it not showing the new templates you created in your fork?

**Comment by srirambv** [comment]
Found it. Going to close this and open a new PR with the changes from forked repo

**Pull request closed without merging**
