### PR TITLE
switch chromium to use github mirror

### PR DESCRIPTION
**Pull request by linhkikuchi**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues/8929) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [x] Android
  - [x] iOS
  - [x] Linux
  - [x] macOS
  - [x] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [x] iOS
  - [x] Linux
  - [x] macOS
  - [x] Windows
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.
- [ ] If adding a new directory with NPM packages, ensure this directory is
  added to `scripts/audit.js`.
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions.

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by bsclifton** [comment]
How up-to-date is the Chromium GitHub repo?

If we wanted to speed up the clone time, we can try to do a clone without history. Since it would only be used for building, that should be fine and should shave a LOT of time off the clone 

cc: @bridiver

**Comment by bridiver** [comment]
@linhkikuchi what is the reason for this? Can you open a ticket for it and also please do not add skip CI tags unless the changes do not apply to those platforms.

**Comment by linhkikuchi** [comment]
> @linhkikuchi what is the reason for this? Can you open a ticket for it and also please do not add skip CI tags unless the changes do not apply to those platforms.

Issue is here https://github.com/brave/brave-browser/issues/8929, we want to speed up the `init` stage on the build, and I did some testing and it is faster if we use github mirror.
WRT the skip CI tags: the first build passed all other platforms except macOS (due to the mac node), that's why I added the skip tags to other platforms to re-run the second build on MacOS only

**Comment by bridiver** [comment]
@linhkikuchi can you update the commit message to auto-close the ticket? You checked the box for `Used Github auto-closing keywords in the commit message.` but I'm not seeing it

**Comment by linhkikuchi** [comment]
> @linhkikuchi can you update the commit message to auto-close the ticket? You checked the box for `Used Github auto-closing keywords in the commit message.` but I'm not seeing it

updated, thanks

**Comment by bridiver** [comment]
it still seems to take a long time with github so maybe another possible solution is to create our own repo with just the tags we use and no other history?

**Comment by linhkikuchi** [comment]
I'm testing out the speed with `fetch --no-history chromium` for both now, and 

> it still seems to take a long time with github so maybe another possible solution is to create our own repo with just the tags we use and no other history?

I have created our own codecommit repo to mirror chromium, but with full mirror, it is very slow. Do we have the lists of the tags that we use? I can try to test with a mirror with just tags we use and no other history

**Comment by bridiver** [comment]
@linhkikuchi you'd have to go back through brave-browser history for https://github.com/brave/brave-browser/blame/master/package.json#L31 and get all the tags we've used. You can probably write some kind of script to do it

**Comment by bridiver** [comment]
@linhkikuchi you could even just trim the history back to `62.0.3202.89` and it would be substantially smaller

**Comment by mihaiplesa** [comment]
@bridiver how would it speed things up by doing that on the git server? we can control what we fetch in npm init or gclient.

**Comment by bridiver** [comment]
as far as I can tell we can't control it. As I said above there is no option for gclient that allows us to make a shallow clone of a specific tag so we either get master (which is never what we want) or we get everything. So the idea is to make "everything" smaller

**Comment by mihaiplesa** [comment]
@bridiver I recall we added `--tags` there only later at https://github.com/brave/brave-browser/search?q=--tags&unscoped_q=--tags

**Comment by mihaiplesa** [comment]
Not very promising https://groups.google.com/a/chromium.org/forum/#!topic/infra-dev/hWJrrccCGhU

**Pull request closed without merging**
