### PR TITLE
only run `gn gen` when creating the output directory

### PR DESCRIPTION
**Pull request by bridiver**
## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.
- [ ] If adding a new directory with NPM packages, ensure this directory is
  added to `scripts/audit.js`.
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions.

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by bridiver** [comment]
unrelated dep issue in CI
```20:01:31  In file included from /Users/jenkins/jenkins/workspace/pr-brave-browser-gn-gen-less/src/brave/chromium_src/content/browser/browser_main_loop.cc:8:
20:01:31  In file included from ../../brave/browser/brave_browser_main_loop.cc:8:
20:01:31  In file included from ../../brave/browser/brave_browser_main_parts.h:10:
20:01:31  ../../chrome/browser/chrome_browser_main.h:18:10: fatal error: 'chrome/common/buildflags.h' file not found
20:01:31  #include "chrome/common/buildflags.h"
20:01:31           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
20:01:31  1 error generated.```

**Comment by petemill** [comment]
Is this because `ninja` automatically regenerates anyway?

```
/Users/petemill/Development/Brave/brave-browser/src
> ninja -C /Users/petemill/Development/Brave/brave-browser/src/out/Component brave -k 1
ninja: Entering directory `/Users/petemill/Development/Brave/brave-browser/src/out/Component'
[1 procs, 1/1 @0.2/s:4.362s]Regenerating ninja files
[4 procs, 9/6222 @7.2/s:1.241s]ACTION //chrome/browser/resou
```

**Comment by bridiver** [comment]
@petemill yes, you only need go call gn gen once and after that everything is automatic so we're just wasting time with it

**Comment by bridiver** [comment]
unrelated error in CI
```20:01:31  In file included from /Users/jenkins/jenkins/workspace/pr-brave-browser-gn-gen-less/src/brave/chromium_src/content/browser/browser_main_loop.cc:8:
20:01:31  In file included from ../../brave/browser/brave_browser_main_loop.cc:8:
20:01:31  In file included from ../../brave/browser/brave_browser_main_parts.h:10:
20:01:31  ../../chrome/browser/chrome_browser_main.h:18:10: fatal error: 'chrome/common/buildflags.h' file not found
20:01:31  #include "chrome/common/buildflags.h"
20:01:31           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
20:01:31  1 error generated.```

**Comment by bridiver** [comment]
seems to be some problem on windows ```18:29:42  > ninja -C C:\less\src\out\Release brave -k 1
18:29:42  ninja: Entering directory `C:\less\src\out\Release'
18:29:42  powershell.exe : ninja: error: loading 'build.ninja': The system cannot find the file specified.
18:29:42  At C:\less@tmp\durable-93a1612c\powershellWrapper.ps1:3 char:1
18:29:42  + & powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -Comm ...
18:29:42  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
18:29:42      + CategoryInfo          : NotSpecified: (ninja: error: l...file specified.:String) [], RemoteException
18:29:42      + FullyQualifiedErrorId : NativeCommandError```

**Comment by bsclifton** [comment]
Closing as stale

**Pull request closed without merging**
