### PR TITLE
prepend depot_tools to the path per chromium build instructions

### PR DESCRIPTION
**Pull request by bridiver**

### CODE REVIEW

**Comment by bridiver** [comment]
this fix was from a muon issue with C66 and corrects a problem that has been around for a long time and we just didn't notice it

**Comment by AlexeyBarabash** [comment]
I had no any issue with that on Linux and Windows because I have add depot_tools to path by myself. Android build on Linux does require that and on Windows I went through Chromium build prerequisite.
But I hadn't add depot_tools on macOS and had not seen any issues :) .

**Comment by bridiver** [comment]
WIP temporarily

**Comment by bridiver** [comment]
@AlexeyBarabash the main issue was on windows which failed to build without the depot_tools path first

**Comment by AlexeyBarabash** [comment]
@bridiver I am still on C65, this explains why I hadn't meet the issue.

**Pull request merged**
